// ─────────────────────────────────────────────────────────────────────────
//  wiki.js — pull real photos and a longer blurb for a place from Wikipedia.
// ─────────────────────────────────────────────────────────────────────────
//  Each place in data/*.js may carry a `wiki` title (an English Wikipedia
//  article name). At runtime we ask Wikipedia's REST API for that article's
//  lead image, a couple of extra photos, and its summary paragraph.
//
//  Why fetch instead of hardcoding image URLs?  Wikipedia resolves the right
//  file for us, so we only have to get the (easy) article title right — no
//  brittle upload.wikimedia.org filenames to keep in sync. The API sends
//  `Access-Control-Allow-Origin: *`, so it works straight from the browser.
//
//  Everything here fails soft: no network (offline) or a bad title just means
//  no photo. The bundled text in each country file always shows regardless.
// ─────────────────────────────────────────────────────────────────────────

const REST = "https://en.wikipedia.org/api/rest_v1/page";
const memory = new Map(); // title → Promise<info> (per session)

// A small, versioned localStorage cache so revisits are instant and work
// even when you're briefly offline after a first online load.
const LS_KEY = "tc_wiki_v2";
const TTL = 1000 * 60 * 60 * 24 * 30; // 30 days
let store = null;

function readStore() {
  if (store) return store;
  try {
    store = JSON.parse(localStorage.getItem(LS_KEY) || "{}");
  } catch {
    store = {};
  }
  return store;
}

function writeStore() {
  try {
    localStorage.setItem(LS_KEY, JSON.stringify(store));
  } catch {
    /* quota or private mode — ignore, we still have the in-memory cache */
  }
}

function cacheGet(title) {
  const s = readStore();
  const hit = s[title];
  if (hit && Date.now() - hit.t < TTL) return hit.v;
  return null;
}

function cacheSet(title, value) {
  const s = readStore();
  s[title] = { t: Date.now(), v: value };
  writeStore();
}

// NOTE: we use image URLs exactly as the API returns them. Wikimedia only
// serves thumbnail widths it has already generated, so rewriting the width in
// a thumb URL (…/330px-File.jpg → …/400px-File.jpg) can 404. The summary
// thumbnail (~320px) is plenty for a list row; the full-res original is used
// for the detail hero, and media-list srcset widths are pre-generated too.

async function fetchJSON(url) {
  const res = await fetch(url, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`wiki ${res.status}`);
  return res.json();
}

// A place's lead image + summary text, plus up to `extra` further photos.
//   → { images: [url, …], thumb: "…", extract: "…", url: "https://en.wikipedia.org/…" }
// Returns { images: [], thumb: "", extract: "", url: "" } on any failure.
export function wikiInfo(title, { extra = 1 } = {}) {
  if (!title) return Promise.resolve({ images: [], thumb: "", extract: "", url: "" });
  if (memory.has(title)) return memory.get(title);

  const cached = cacheGet(title);
  if (cached) {
    const p = Promise.resolve(cached);
    memory.set(title, p);
    return p;
  }

  const p = (async () => {
    const out = { images: [], thumb: "", extract: "", url: "" };
    try {
      const sum = await fetchJSON(`${REST}/summary/${encodeURIComponent(title)}`);
      // A light, already-sized thumbnail (~320px) for the list rows.
      out.thumb = (sum.thumbnail && sum.thumbnail.source) || "";
      out.extract = sum.extract || "";
      out.url =
        (sum.content_urls &&
          sum.content_urls.desktop &&
          sum.content_urls.desktop.page) ||
        `https://en.wikipedia.org/wiki/${encodeURIComponent(title)}`;

      // Build the gallery from the article's media-list: these srcset URLs are
      // pre-generated by Wikimedia at moderate widths (~500–1000px), so they
      // load fast and reliably — unlike multi-megabyte full-resolution originals.
      if (extra >= 0) {
        try {
          const media = await fetchJSON(`${REST}/media-list/${encodeURIComponent(title)}`);
          const seen = new Set();
          for (const item of media.items || []) {
            if (out.images.length >= 1 + extra) break;
            if (item.type !== "image") continue;
            const src = pickSrc(item); // largest pre-generated size
            if (!src || !/\.(jpe?g|png)$/i.test(src.split("?")[0])) continue;
            const key = baseName(src);
            if (seen.has(key)) continue;
            seen.add(key);
            out.images.push(src);
          }
        } catch {
          /* media-list unavailable — fall back to the summary image below */
        }
      }

      // Fallback: if the media-list gave us nothing, use the summary thumbnail.
      if (!out.images.length && out.thumb) out.images.push(out.thumb);
    } catch {
      /* offline or unknown title — leave the empty result */
    }
    cacheSet(title, out);
    return out;
  })();

  memory.set(title, p);
  return p;
}

// A small, list-sized photo (the summary thumbnail) for the place-row thumbnails.
export async function wikiThumb(title) {
  const info = await wikiInfo(title, { extra: 0 });
  return info.thumb || info.images[0] || "";
}

// The bare file name, sans size prefix, to dedupe lead vs. gallery images.
function baseName(url) {
  const last = url.split("/").pop() || "";
  return last.replace(/^\d+px-/, "").toLowerCase();
}

// media-list items give a srcset (1x/1.5x/2x, protocol-relative) or a src.
// Take the highest-resolution entry — still a pre-generated, sensible width.
function pickSrc(item) {
  let src = "";
  const ss = item.srcset || [];
  if (ss.length) src = ss[ss.length - 1].src;
  else if (item.src) src = item.src;
  if (src && src.startsWith("//")) src = "https:" + src;
  return src;
}
